// execute_file(main_directory_const+"\SCR\LOAD\scr_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\set_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\spr_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\bg_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\snd_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\mdl_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\coll_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\obj_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\rm_load_scr.gml");
execute_file(main_directory_const+"\SCR\LOAD\zone_load_scr.gml");
// Gay
global.pride_list = ds_list_create();
ds_list_clear(global.pride_list);
ds_list_add(global.pride_list,pride_color_obj);
ds_list_add(global.pride_list,abro_color_obj);
ds_list_add(global.pride_list,ace_color_obj);
//ds_list_add(global.pride_list,aceflux_color_obj);
ds_list_add(global.pride_list,agender_color_obj);
ds_list_add(global.pride_list,aro_color_obj);
ds_list_add(global.pride_list,aroace_color_obj);
ds_list_add(global.pride_list,bi_color_obj);
ds_list_add(global.pride_list,bigender_color_obj);
ds_list_add(global.pride_list,demiboy_color_obj);
ds_list_add(global.pride_list,demigirl_color_obj);
ds_list_add(global.pride_list,enby_color_obj);
ds_list_add(global.pride_list,gay_color_obj);
ds_list_add(global.pride_list,genderfluid_color_obj);
ds_list_add(global.pride_list,genderflux_color_obj);
ds_list_add(global.pride_list,genderqueer_color_obj);
ds_list_add(global.pride_list,grayce_color_obj);
ds_list_add(global.pride_list,grayro_color_obj);
ds_list_add(global.pride_list,lesbian_color_obj);
ds_list_add(global.pride_list,maverique_color_obj);
ds_list_add(global.pride_list,omni_color_obj);
ds_list_add(global.pride_list,pan_color_obj);
ds_list_add(global.pride_list,pangender_color_obj);
ds_list_add(global.pride_list,polyce_color_obj);
ds_list_add(global.pride_list,queer_color_obj);
ds_list_add(global.pride_list,trans_color_obj);
ds_list_add(global.pride_list,transfem_color_obj);
ds_list_add(global.pride_list,transmasc_color_obj);
ds_list_add(global.pride_list,trigender_color_obj);
ds_list_add(global.pride_list,xenogender_color_obj);
// Set variables
texture_set_repeat(true);
action_set_cursor(-1,false);
draw_set_color(c_white);
draw_set_alpha(1);
d3d_set_lighting(false);
d3d_set_culling(false);
d3d_set_hidden(false);
draw_set_font(main_font);
// Load
instance_create(0,0,global.control_obj);
room_goto(menu_rm);