ini_open("settings.ini");
global.fov_var = ini_read_real("MAIN","fov",fov_const);
global.fps_var = ini_read_real("MAIN","fps",fps_const);
global.tps_var = ini_read_real("MAIN","tps",tps_const);
global.sens_var = ini_read_real("MAIN","sens",sens_const);
global.vol_var = ini_read_real("MAIN","vol",vol_const);
global.vol_var /= 100;
global.reduce_flash_var = ini_read_real("MAIN","reduce_flash",reduce_flash_const);
global.max_part_var = ini_read_real("MAIN","max_part",max_part_const);
global.can_crouch_var = ini_read_real("MAIN","crouch",crouch_const);
global.crouch_toggle_var = ini_read_real("MAIN","crouch_toggle",crouch_toggle_const);
global.can_jump_var = ini_read_real("MAIN","jump",jump_const);
global.sub_var = ini_read_real("MAIN","sub",sub_const);
global.anti_alias_var = ini_read_real("MAIN","anti_alias",anti_alias_const);
global.vsync_var = ini_read_real("MAIN","vsync",vsync_const);
global.fullscreen_var = ini_read_real("MAIN","fullscreen",fullscreen_const);
global.color_var = ini_read_real("MAIN","color",color_const);
global.coll_prec_var = ini_read_real("MAIN","coll_prec",coll_prec_const);
global.game_spd_var = ini_read_real("MAIN","game_spd",game_spd_const);
global.move_bob_var = ini_read_real("MAIN","move_bob",move_bob_const);
global.idle_bob_var = ini_read_real("MAIN","idle_bob",idle_bob_const);
global.shake_type_var = ini_read_real("MAIN","shake_type",shake_modern_const);
// Controls
global.up_key_var = ini_read_real("CONTROL","up_key_var",87);
global.down_key_var = ini_read_real("CONTROL","down_key_var",83);
global.left_key_var = ini_read_real("CONTROL","left_key_var",65);
global.right_key_var = ini_read_real("CONTROL","right_key_var",68);
global.confirm_key_var = ini_read_real("CONTROL","confirm_key_var",69);
global.back_key_var = ini_read_real("CONTROL","back_key_var",27);
global.forward_key_var = ini_read_real("CONTROL","forward_key_var",87);
global.backward_key_var = ini_read_real("CONTROL","backward_key_var",83);
global.strafe_left_key_var = ini_read_real("CONTROL","strafe_left_key_var",65);
global.strafe_right_key_var = ini_read_real("CONTROL","strafe_right_key_var",68);
global.interact_key_var = ini_read_real("CONTROL","interact_key_var",69);
global.sprint_key_var = ini_read_real("CONTROL","sprint_key_var",16);
global.jump_key_var = ini_read_real("CONTROL","jump_key_var",32);
global.crouch_key_var = ini_read_real("CONTROL","crouch_key_var",17);
global.attack_key_var = ini_read_real("CONTROL","attack_key_var",17);
global.pause_key_var = ini_read_real("CONTROL","pause_key_var",27);
global.debug_key_var = ini_read_real("CONTROL","debug_key_var",45);
global.turnaround_key_var = ini_read_real("CONTROL","turnaround_key_var",81);
ini_close();
// This should happen when a game starts, but we don't have a menu right now
ini_open("save_ex.ini");
// Main
global.rm_count_var = ini_read_real("SETTING","rm_count",0);
global.violence_var = ini_read_real("SETTING","violence",0);
global.note_var = ini_read_real("SETTING","note",0);
// Settings
global.stam_per_var = ini_read_real("SETTING","stam_per",false);
global.fall_var = ini_read_real("SETTING","fall",false);
global.lock_var = ini_read_real("SETTING","lock",1);
global.dmg_shake_var = ini_read_real("SETTING","dmg_shake",false);
global.multi_type_var = ini_read_real("SETTING","multi_type",0);
global.multi_min_var = ini_read_real("SETTING","multi_min",1);
global.multi_max_var = ini_read_real("SETTING","multi_max",5);
global.multi_start_var = ini_read_real("SETTING","multi_start",1000);
global.multi_end_var = ini_read_real("SETTING","multi_end",2000);
global.count_type_var = ini_read_real("SETTING","count_type",0);
global.count_min_var = ini_read_real("SETTING","count_min",0);
global.count_max_var = ini_read_real("SETTING","count_max",20);
global.count_start_var = ini_read_real("SETTING","count_start",1000);
global.count_end_var = ini_read_real("SETTING","count_end",2000);
global.mode_var = ini_read_real("SETTING","mode",1);
// Behavior stuff
global.default_type_var = ini_read_real("BEHAVIOR","type",0);
global.player_type_var = ini_read_real("BEHAVIOR","player_type",global.default_type_var);
global.axe_type_var = ini_read_real("BEHAVIOR","axe_type",global.default_type_var);
global.gel_type_var = ini_read_real("BEHAVIOR","gel_type",global.default_type_var);
global.bug_type_var = ini_read_real("BEHAVIOR","bug_type",global.default_type_var);
global.ringu_type_var = ini_read_real("BEHAVIOR","ringu_type",global.default_type_var);
global.bab_type_var = ini_read_real("BEHAVIOR","bab_type",global.default_type_var);
global.pup_type_var = ini_read_real("BEHAVIOR","pup_type",global.default_type_var);
global.flesh_type_var = ini_read_real("BEHAVIOR","flesh_type",global.default_type_var);
global.dl_type_var = ini_read_real("BEHAVIOR","dl_type",global.default_type_var);
global.taker_type_var = ini_read_real("BEHAVIOR","taker_type",global.default_type_var);
global.para_type_var = ini_read_real("BEHAVIOR","para_type",global.default_type_var);
global.fd_type_var = ini_read_real("BEHAVIOR","fd_type",global.default_type_var);
global.killer_type_var = ini_read_real("BEHAVIOR","killer_type",global.default_type_var);
global.mur_type_var = ini_read_real("BEHAVIOR","mur_type",global.default_type_var);
global.sg_type_var = ini_read_real("BEHAVIOR","sg_type",global.default_type_var);
global.body_type_var = ini_read_real("BEHAVIOR","body_type",global.default_type_var);
global.stem_type_var = ini_read_real("BEHAVIOR","stem_type",global.default_type_var);
global.patient_type_var = ini_read_real("BEHAVIOR","patient_type",global.default_type_var);
global.cow_type_var = ini_read_real("BEHAVIOR","cow_type",global.default_type_var);
global.bekka_type_var = ini_read_real("BEHAVIOR","bekka_type",global.default_type_var);
global.husk_type_var = ini_read_real("BEHAVIOR","husk_type",global.default_type_var);
global.wc_type_var = ini_read_real("BEHAVIOR","wc_type",global.default_type_var);
global.clown_type_var = ini_read_real("BEHAVIOR","clown_type",global.default_type_var);
global.hd_type_var = ini_read_real("BEHAVIOR","hd_type",global.default_type_var);
global.frenzy_type_var = ini_read_real("BEHAVIOR","frenzy_type",global.default_type_var);
global.real_ringu_type_var = ini_read_real("BEHAVIOR","real_ringu_type",global.default_type_var);
global.tiri_type_var = ini_read_real("BEHAVIOR","tiri_type",global.default_type_var);
global.lisa_type_var = ini_read_real("BEHAVIOR","lisa_type",global.default_type_var);
global.otto_type_var = ini_read_real("BEHAVIOR","otto_type",global.default_type_var);
global.spooper_type_var = ini_read_real("BEHAVIOR","spooper_type",global.default_type_var);
global.wf_type_var = ini_read_real("BEHAVIOR","wf_type",global.default_type_var);
ini_close();
// Set stuff
window_set_fullscreen(global.fullscreen_var);
set_synchronization(global.vsync_var);
texture_set_interpolation(global.anti_alias_var);