global.zone_len_var = 9;
// Zone 0
global.zone_arr[0] = ds_list_create();
ds_list_clear(global.zone_arr[0]);
ds_list_add(global.zone_arr[0],hall_01_rm); ds_list_add(global.zone_arr[0],hall_01_rm); ds_list_add(global.zone_arr[0],hall_01_rm); ds_list_add(global.zone_arr[0],hall_01_rm); ds_list_add(global.zone_arr[0],hall_01_rm); ds_list_add(global.zone_arr[0],hall_01_rm);
ds_list_add(global.zone_arr[0],hall_02_a_rm); ds_list_add(global.zone_arr[0],hall_02_a_rm); ds_list_add(global.zone_arr[0],hall_02_a_rm); ds_list_add(global.zone_arr[0],hall_02_a_rm);
ds_list_add(global.zone_arr[0],hall_02_b_rm); ds_list_add(global.zone_arr[0],hall_02_b_rm);
ds_list_add(global.zone_arr[0],hall_03_rm); ds_list_add(global.zone_arr[0],hall_03_rm); ds_list_add(global.zone_arr[0],hall_03_rm); ds_list_add(global.zone_arr[0],hall_03_rm);
ds_list_add(global.zone_arr[0],hall_04_rm); ds_list_add(global.zone_arr[0],hall_04_rm);
ds_list_add(global.zone_arr[0],hall_05_a_rm); ds_list_add(global.zone_arr[0],hall_05_a_rm);
ds_list_add(global.zone_arr[0],hall_05_b_rm); ds_list_add(global.zone_arr[0],hall_05_b_rm);
ds_list_add(global.zone_arr[0],hall_05_c_rm); ds_list_add(global.zone_arr[0],hall_05_c_rm);
ds_list_add(global.zone_arr[0],hall_06_a_rm);
ds_list_add(global.zone_arr[0],hall_06_b_rm);
ds_list_add(global.zone_arr[0],hall_07_a_rm);
ds_list_add(global.zone_arr[0],hall_07_b_rm);
ds_list_add(global.zone_arr[0],hall_08_rm); ds_list_add(global.zone_arr[0],hall_08_rm);
ds_list_add(global.zone_arr[0],hall_09_a_rm);
ds_list_add(global.zone_arr[0],hall_09_b_rm);
ds_list_add(global.zone_arr[0],hall_10_a_rm);
ds_list_add(global.zone_arr[0],hall_10_b_rm);
ds_list_add(global.zone_arr[0],hall_11_a_rm);
ds_list_add(global.zone_arr[0],hall_11_b_rm);
ds_list_add(global.zone_arr[0],hall_12_a_rm);
ds_list_add(global.zone_arr[0],hall_12_b_rm);
ds_list_add(global.zone_arr[0],hall_19_rm); ds_list_add(global.zone_arr[0],hall_19_rm);
ds_list_add(global.zone_arr[0],hall_20_rm); ds_list_add(global.zone_arr[0],hall_20_rm);
ds_list_add(global.zone_arr[0],hall_21_a_rm); ds_list_add(global.zone_arr[0],hall_21_a_rm);
ds_list_add(global.zone_arr[0],hall_21_b_rm); ds_list_add(global.zone_arr[0],hall_21_b_rm);
ds_list_add(global.zone_arr[0],hall_22_rm); ds_list_add(global.zone_arr[0],hall_22_rm);
ds_list_add(global.zone_arr[0],hall_23_rm); ds_list_add(global.zone_arr[0],hall_23_rm);
ds_list_add(global.zone_arr[0],hall_24_rm); ds_list_add(global.zone_arr[0],hall_24_rm);
ds_list_add(global.zone_arr[0],hall_26_rm); ds_list_add(global.zone_arr[0],hall_26_rm);
ds_list_add(global.zone_arr[0],hall_27_rm); ds_list_add(global.zone_arr[0],hall_27_rm);
ds_list_add(global.zone_arr[0],hall_30_rm); ds_list_add(global.zone_arr[0],hall_30_rm);
ds_list_add(global.zone_arr[0],hall_31_rm); ds_list_add(global.zone_arr[0],hall_31_rm);
ds_list_add(global.zone_arr[0],hall_32_rm); ds_list_add(global.zone_arr[0],hall_32_rm);
ds_list_add(global.zone_arr[0],hall_33_rm); ds_list_add(global.zone_arr[0],hall_33_rm);
ds_list_add(global.zone_arr[0],hall_34_rm); ds_list_add(global.zone_arr[0],hall_34_rm);
ds_list_add(global.zone_arr[0],sm_01_rm); ds_list_add(global.zone_arr[0],sm_01_rm);
ds_list_add(global.zone_arr[0],sm_02_rm); ds_list_add(global.zone_arr[0],sm_02_rm);
ds_list_add(global.zone_arr[0],sm_03_rm); ds_list_add(global.zone_arr[0],sm_03_rm);
ds_list_add(global.zone_arr[0],purp_01_rm); ds_list_add(global.zone_arr[0],purp_01_rm);
ds_list_add(global.zone_arr[0],purp_02_rm); ds_list_add(global.zone_arr[0],purp_02_rm);
ds_list_add(global.zone_arr[0],purp_03_rm); ds_list_add(global.zone_arr[0],purp_03_rm);
ds_list_add(global.zone_arr[0],purp_04_rm); ds_list_add(global.zone_arr[0],purp_04_rm);
ds_list_add(global.zone_arr[0],purp_05_rm); ds_list_add(global.zone_arr[0],purp_05_rm);
ds_list_add(global.zone_arr[0],purp_06_rm); ds_list_add(global.zone_arr[0],purp_06_rm);
ds_list_add(global.zone_arr[0],sm_15_rm); ds_list_add(global.zone_arr[0],sm_15_rm);
ds_list_add(global.zone_arr[0],sm_16_rm); ds_list_add(global.zone_arr[0],sm_16_rm);
ds_list_add(global.zone_arr[0],sm_17_rm); ds_list_add(global.zone_arr[0],sm_17_rm);
ds_list_add(global.zone_arr[0],sm_18_rm); ds_list_add(global.zone_arr[0],sm_18_rm);
ds_list_add(global.zone_arr[0],sm_19_rm); ds_list_add(global.zone_arr[0],sm_19_rm);
ds_list_add(global.zone_arr[0],sm_20_rm); ds_list_add(global.zone_arr[0],sm_20_rm);
// ds_list_add(global.zone_arr[0],bed_01_rm); ds_list_add(global.zone_arr[0],bed_01_rm); ds_list_add(global.zone_arr[0],bed_01_rm); ds_list_add(global.zone_arr[0],bed_01_rm);
// ds_list_add(global.zone_arr[0],bed_02_rm); ds_list_add(global.zone_arr[0],bed_02_rm); ds_list_add(global.zone_arr[0],bed_02_rm); ds_list_add(global.zone_arr[0],bed_02_rm);
// ds_list_add(global.zone_arr[0],bed_03_rm); ds_list_add(global.zone_arr[0],bed_03_rm); ds_list_add(global.zone_arr[0],bed_03_rm); ds_list_add(global.zone_arr[0],bed_03_rm);
// ds_list_add(global.zone_arr[0],bed_04_rm); ds_list_add(global.zone_arr[0],bed_04_rm);
// ds_list_add(global.zone_arr[0],bed_05_rm); ds_list_add(global.zone_arr[0],bed_05_rm);
// ds_list_add(global.zone_arr[0],bed_06_rm); ds_list_add(global.zone_arr[0],bed_06_rm);
ds_list_add(global.zone_arr[0],med_01_rm); ds_list_add(global.zone_arr[0],med_01_rm);
ds_list_add(global.zone_arr[0],med_02_rm); ds_list_add(global.zone_arr[0],med_02_rm);
ds_list_add(global.zone_arr[0],med_03_rm); ds_list_add(global.zone_arr[0],med_03_rm);
ds_list_add(global.zone_arr[0],med_04_rm); ds_list_add(global.zone_arr[0],med_04_rm);
ds_list_add(global.zone_arr[0],med_05_rm); ds_list_add(global.zone_arr[0],med_05_rm);
ds_list_add(global.zone_arr[0],med_06_rm); ds_list_add(global.zone_arr[0],med_06_rm);
ds_list_add(global.zone_arr[0],med_07_rm); ds_list_add(global.zone_arr[0],med_07_rm);
ds_list_add(global.zone_arr[0],med_08_rm); ds_list_add(global.zone_arr[0],med_08_rm);
ds_list_add(global.zone_arr[0],med_09_rm); ds_list_add(global.zone_arr[0],med_09_rm);
ds_list_add(global.zone_arr[0],med_10_rm); ds_list_add(global.zone_arr[0],med_10_rm);
ds_list_add(global.zone_arr[0],med_11_rm); ds_list_add(global.zone_arr[0],med_11_rm);
// ds_list_add(global.zone_arr[0],stor_01_rm); ds_list_add(global.zone_arr[0],stor_01_rm);
// ds_list_add(global.zone_arr[0],stor_02_rm); ds_list_add(global.zone_arr[0],stor_02_rm);
// ds_list_add(global.zone_arr[0],stor_03_rm); ds_list_add(global.zone_arr[0],stor_03_rm);
// ds_list_add(global.zone_arr[0],stor_04_rm); ds_list_add(global.zone_arr[0],stor_04_rm);
// ds_list_add(global.zone_arr[0],stor_05_rm); ds_list_add(global.zone_arr[0],stor_05_rm);
// ds_list_add(global.zone_arr[0],stor_06_rm); ds_list_add(global.zone_arr[0],stor_06_rm);
// ds_list_add(global.zone_arr[0],stor_07_rm); ds_list_add(global.zone_arr[0],stor_07_rm);
// ds_list_add(global.zone_arr[0],stor_08_rm); ds_list_add(global.zone_arr[0],stor_08_rm);
// Zone 1
global.zone_arr[1] = ds_list_create();
ds_list_clear(global.zone_arr[1]);
// ds_list_add(global.zone_arr[1],chasm_01_rm);
// ds_list_add(global.zone_arr[1],chasm_02_rm);
// ds_list_add(global.zone_arr[1],chasm_03_rm);
// ds_list_add(global.zone_arr[1],chasm_04_rm);
// ds_list_add(global.zone_arr[1],chasm_05_rm);
// ds_list_add(global.zone_arr[1],chasm_06_rm);
// ds_list_add(global.zone_arr[1],chasm_07_rm);
// ds_list_add(global.zone_arr[1],chasm_08_rm);
// ds_list_add(global.zone_arr[1],chasm_09_rm);
// ds_list_add(global.zone_arr[1],chasm_10_rm);
// ds_list_add(global.zone_arr[1],chasm_11_rm);
// ds_list_add(global.zone_arr[1],chasm_12_rm);
// ds_list_add(global.zone_arr[1],chasm_13_rm);
// ds_list_add(global.zone_arr[1],chasm_14_rm);
// ds_list_add(global.zone_arr[1],chasm_15_rm);
// ds_list_add(global.zone_arr[1],chasm_16_rm);
ds_list_add(global.zone_arr[1],engine_01_rm);
ds_list_add(global.zone_arr[1],engine_02_rm);
ds_list_add(global.zone_arr[1],engine_03_rm);
ds_list_add(global.zone_arr[1],engine_04_rm);
ds_list_add(global.zone_arr[1],engine_05_rm);
ds_list_add(global.zone_arr[1],engine_06_rm);
ds_list_add(global.zone_arr[1],engine_07_rm);
ds_list_add(global.zone_arr[1],engine_08_rm);
ds_list_add(global.zone_arr[1],engine_09_rm);
ds_list_add(global.zone_arr[1],engine_10_rm);
ds_list_add(global.zone_arr[1],engine_11_rm);
ds_list_add(global.zone_arr[1],engine_12_rm);
ds_list_add(global.zone_arr[1],engine_13_rm);
ds_list_add(global.zone_arr[1],engine_14_rm);
ds_list_add(global.zone_arr[1],engine_15_rm);
ds_list_add(global.zone_arr[1],engine_16_rm);
ds_list_add(global.zone_arr[1],big_01_rm);
ds_list_add(global.zone_arr[1],big_02_rm);
ds_list_add(global.zone_arr[1],big_03_rm);
ds_list_add(global.zone_arr[1],big_04_rm);
ds_list_add(global.zone_arr[1],big_05_rm);
ds_list_add(global.zone_arr[1],big_06_rm);
ds_list_add(global.zone_arr[1],big_07_rm);
ds_list_add(global.zone_arr[1],big_08_rm);
ds_list_add(global.zone_arr[1],long_hall_01_rm);
ds_list_add(global.zone_arr[1],long_hall_02_rm);
ds_list_add(global.zone_arr[1],long_hall_03_rm);
ds_list_add(global.zone_arr[1],long_hall_04_rm);
ds_list_add(global.zone_arr[1],long_hall_05_rm); ds_list_add(global.zone_arr[1],long_hall_05_rm);
ds_list_add(global.zone_arr[1],long_hall_07_rm);
ds_list_add(global.zone_arr[1],long_hall_08_rm);
ds_list_add(global.zone_arr[1],long_hall_09_rm);
ds_list_add(global.zone_arr[1],long_hall_10_rm);
ds_list_add(global.zone_arr[1],long_hall_11_rm);
ds_list_add(global.zone_arr[1],long_hall_12_rm);
ds_list_add(global.zone_arr[1],w_hall_01_rm);
ds_list_add(global.zone_arr[1],w_hall_02_rm);
ds_list_add(global.zone_arr[1],w_hall_03_rm);
ds_list_add(global.zone_arr[1],w_hall_04_rm);
ds_list_add(global.zone_arr[1],w_hall_05_rm);
ds_list_add(global.zone_arr[1],w_hall_06_rm);
ds_list_add(global.zone_arr[1],w_hall_07_rm);
ds_list_add(global.zone_arr[1],w_hall_08_rm);
ds_list_add(global.zone_arr[1],w_hall_09_rm);
ds_list_add(global.zone_arr[1],w_hall_10_rm);
ds_list_add(global.zone_arr[1],w_hall_11_a_rm);
ds_list_add(global.zone_arr[1],w_hall_11_b_rm);
ds_list_add(global.zone_arr[1],w_hall_12_rm);
ds_list_add(global.zone_arr[1],w_hall_13_rm);
ds_list_add(global.zone_arr[1],w_hall_14_rm);
ds_list_add(global.zone_arr[1],w_hall_15_rm);
// Zone 2
global.zone_arr[2] = ds_list_create();
ds_list_clear(global.zone_arr[2]);
// ds_list_add(global.zone_arr[2],chasm_01_rm);
// ds_list_add(global.zone_arr[2],chasm_02_rm);
// ds_list_add(global.zone_arr[2],chasm_03_rm);
// ds_list_add(global.zone_arr[2],chasm_04_rm);
// ds_list_add(global.zone_arr[2],chasm_05_rm);
// ds_list_add(global.zone_arr[2],chasm_06_rm);
// ds_list_add(global.zone_arr[2],chasm_07_rm);
// ds_list_add(global.zone_arr[2],chasm_08_rm);
// ds_list_add(global.zone_arr[2],chasm_09_rm);
// ds_list_add(global.zone_arr[2],chasm_10_rm);
// ds_list_add(global.zone_arr[2],chasm_11_rm);
// ds_list_add(global.zone_arr[2],chasm_12_rm);
// ds_list_add(global.zone_arr[2],chasm_13_rm);
// ds_list_add(global.zone_arr[2],chasm_14_rm);
// ds_list_add(global.zone_arr[2],chasm_15_rm);
// ds_list_add(global.zone_arr[2],chasm_16_rm);
// ds_list_add(global.zone_arr[2],dun_01_rm);
// ds_list_add(global.zone_arr[2],dun_02_rm);
// ds_list_add(global.zone_arr[2],dun_03_rm);
// ds_list_add(global.zone_arr[2],dun_04_rm);
// ds_list_add(global.zone_arr[2],dun_05_rm);
// ds_list_add(global.zone_arr[2],dun_06_rm);
// ds_list_add(global.zone_arr[2],dun_07_rm);
// ds_list_add(global.zone_arr[2],dun_08_rm);
// ds_list_add(global.zone_arr[2],dun_09_rm);
// ds_list_add(global.zone_arr[2],dun_10_rm);
// ds_list_add(global.zone_arr[2],dun_11_rm);
// ds_list_add(global.zone_arr[2],dun_12_rm);
// ds_list_add(global.zone_arr[2],dun_13_rm);
// ds_list_add(global.zone_arr[2],dun_14_rm);
// ds_list_add(global.zone_arr[2],dun_15_rm);
// ds_list_add(global.zone_arr[2],dun_16_rm);
ds_list_add(global.zone_arr[2],jail_01_rm);
ds_list_add(global.zone_arr[2],jail_02_rm);
ds_list_add(global.zone_arr[2],jail_03_rm);
ds_list_add(global.zone_arr[2],jail_04_rm);
ds_list_add(global.zone_arr[2],jail_05_rm);
ds_list_add(global.zone_arr[2],jail_06_a_rm);
ds_list_add(global.zone_arr[2],jail_07_a_rm);
ds_list_add(global.zone_arr[2],jail_08_rm);
ds_list_add(global.zone_arr[2],jail_09_rm);
ds_list_add(global.zone_arr[2],jail_10_a_rm);
ds_list_add(global.zone_arr[2],jail_11_rm);
ds_list_add(global.zone_arr[2],jail_12_rm);
ds_list_add(global.zone_arr[2],jail_13_rm);
ds_list_add(global.zone_arr[2],jail_14_rm);
ds_list_add(global.zone_arr[2],jail_15_rm);
ds_list_add(global.zone_arr[2],jail_16_rm);
ds_list_add(global.zone_arr[2],w_hall_01_rm);
ds_list_add(global.zone_arr[2],w_hall_02_rm);
ds_list_add(global.zone_arr[2],w_hall_03_rm);
ds_list_add(global.zone_arr[2],w_hall_04_rm);
ds_list_add(global.zone_arr[2],w_hall_05_rm);
ds_list_add(global.zone_arr[2],w_hall_06_rm);
ds_list_add(global.zone_arr[2],w_hall_07_rm);
ds_list_add(global.zone_arr[2],w_hall_08_rm);
ds_list_add(global.zone_arr[2],w_hall_09_rm);
ds_list_add(global.zone_arr[2],w_hall_10_rm);
ds_list_add(global.zone_arr[2],w_hall_11_a_rm);
ds_list_add(global.zone_arr[2],w_hall_11_b_rm);
ds_list_add(global.zone_arr[2],w_hall_12_rm);
ds_list_add(global.zone_arr[2],w_hall_13_rm);
ds_list_add(global.zone_arr[2],w_hall_14_rm);
ds_list_add(global.zone_arr[2],w_hall_15_rm);
ds_list_add(global.zone_arr[2],med_01_rm);
ds_list_add(global.zone_arr[2],med_02_rm);
ds_list_add(global.zone_arr[2],med_03_rm);
ds_list_add(global.zone_arr[2],med_04_rm);
ds_list_add(global.zone_arr[2],med_05_rm);
ds_list_add(global.zone_arr[2],med_06_rm);
ds_list_add(global.zone_arr[2],med_07_rm);
ds_list_add(global.zone_arr[2],med_08_rm);
ds_list_add(global.zone_arr[2],med_09_rm);
ds_list_add(global.zone_arr[2],med_10_rm);
ds_list_add(global.zone_arr[2],med_11_rm);
ds_list_add(global.zone_arr[2],hall_02_b_rm);
ds_list_add(global.zone_arr[2],hall_05_c_rm);
ds_list_add(global.zone_arr[2],hall_21_b_rm);
ds_list_add(global.zone_arr[2],hall_24_rm);
ds_list_add(global.zone_arr[2],hall_26_rm);
ds_list_add(global.zone_arr[2],hall_27_rm);
ds_list_add(global.zone_arr[2],hall_30_rm);
ds_list_add(global.zone_arr[2],hall_31_rm);
ds_list_add(global.zone_arr[2],hall_32_rm);
ds_list_add(global.zone_arr[2],hall_33_rm);
ds_list_add(global.zone_arr[2],hall_34_rm);
// Zone 3
global.zone_arr[3] = ds_list_create();
ds_list_clear(global.zone_arr[3]);
ds_list_add(global.zone_arr[3],sc_hall_01_rm);
ds_list_add(global.zone_arr[3],sc_hall_02_rm);
ds_list_add(global.zone_arr[3],sc_hall_03_rm);
ds_list_add(global.zone_arr[3],sc_hall_04_rm);
ds_list_add(global.zone_arr[3],sc_hall_05_rm);
ds_list_add(global.zone_arr[3],sc_hall_06_rm);
ds_list_add(global.zone_arr[3],sc_hall_07_rm);
ds_list_add(global.zone_arr[3],sc_hall_08_rm);
ds_list_add(global.zone_arr[3],sc_hall_09_rm);
ds_list_add(global.zone_arr[3],sc_hall_10_rm);
ds_list_add(global.zone_arr[3],sc_hall_11_rm);
ds_list_add(global.zone_arr[3],sc_hall_12_rm);
/*
ds_list_add(global.zone_arr[3],hotel_01_rm);
ds_list_add(global.zone_arr[3],hotel_02_rm);
ds_list_add(global.zone_arr[3],hotel_03_rm);
ds_list_add(global.zone_arr[3],hotel_04_rm);
ds_list_add(global.zone_arr[3],hotel_05_rm);
ds_list_add(global.zone_arr[3],hotel_06_rm);
ds_list_add(global.zone_arr[3],hotel_07_rm);
ds_list_add(global.zone_arr[3],hotel_08_rm);
ds_list_add(global.zone_arr[3],hotel_09_rm);
ds_list_add(global.zone_arr[3],hotel_10_rm);
ds_list_add(global.zone_arr[3],hotel_11_rm);
ds_list_add(global.zone_arr[3],hotel_12_rm);
ds_list_add(global.zone_arr[3],hotel_13_rm);
ds_list_add(global.zone_arr[3],hotel_14_rm);
ds_list_add(global.zone_arr[3],hotel_15_rm);
ds_list_add(global.zone_arr[3],hotel_16_rm);
*/
ds_list_add(global.zone_arr[3],med_s_01_rm);
ds_list_add(global.zone_arr[3],med_s_02_rm);
ds_list_add(global.zone_arr[3],med_s_03_rm);
ds_list_add(global.zone_arr[3],med_s_04_rm);
ds_list_add(global.zone_arr[3],med_s_05_rm);
ds_list_add(global.zone_arr[3],med_s_06_rm);
ds_list_add(global.zone_arr[3],med_s_07_rm);
ds_list_add(global.zone_arr[3],med_s_08_rm);
ds_list_add(global.zone_arr[3],med_s_09_rm);
ds_list_add(global.zone_arr[3],med_s_10_rm);
ds_list_add(global.zone_arr[3],med_s_11_rm);
ds_list_add(global.zone_arr[3],med_s_12_rm);
ds_list_add(global.zone_arr[3],long_hall_01_rm);
ds_list_add(global.zone_arr[3],long_hall_02_rm);
ds_list_add(global.zone_arr[3],long_hall_03_rm);
ds_list_add(global.zone_arr[3],long_hall_04_rm);
ds_list_add(global.zone_arr[3],long_hall_05_rm); ds_list_add(global.zone_arr[3],long_hall_05_rm);
ds_list_add(global.zone_arr[3],long_hall_07_rm);
ds_list_add(global.zone_arr[3],long_hall_08_rm);
ds_list_add(global.zone_arr[3],long_hall_09_rm);
ds_list_add(global.zone_arr[3],long_hall_10_rm);
ds_list_add(global.zone_arr[3],long_hall_11_rm);
ds_list_add(global.zone_arr[3],long_hall_12_rm);
ds_list_add(global.zone_arr[3],med_01_rm);
ds_list_add(global.zone_arr[3],med_02_rm);
ds_list_add(global.zone_arr[3],med_03_rm);
ds_list_add(global.zone_arr[3],med_04_rm);
ds_list_add(global.zone_arr[3],med_05_rm);
ds_list_add(global.zone_arr[3],med_06_rm);
ds_list_add(global.zone_arr[3],med_07_rm);
ds_list_add(global.zone_arr[3],med_08_rm);
ds_list_add(global.zone_arr[3],med_09_rm);
ds_list_add(global.zone_arr[3],med_10_rm);
ds_list_add(global.zone_arr[3],med_11_rm);
// Zone 4
global.zone_arr[4] = ds_list_create();
ds_list_clear(global.zone_arr[4]);
ds_list_add(global.zone_arr[4],hall_01_rm); ds_list_add(global.zone_arr[4],hall_01_rm);
ds_list_add(global.zone_arr[4],hall_02_a_rm); ds_list_add(global.zone_arr[4],hall_02_a_rm);
ds_list_add(global.zone_arr[4],hall_02_b_rm); ds_list_add(global.zone_arr[4],hall_02_b_rm);
ds_list_add(global.zone_arr[4],hall_03_rm); ds_list_add(global.zone_arr[4],hall_03_rm);
ds_list_add(global.zone_arr[4],hall_04_rm); ds_list_add(global.zone_arr[4],hall_04_rm);
ds_list_add(global.zone_arr[4],hall_05_a_rm); ds_list_add(global.zone_arr[4],hall_05_a_rm);
ds_list_add(global.zone_arr[4],hall_05_b_rm); ds_list_add(global.zone_arr[4],hall_05_b_rm);
ds_list_add(global.zone_arr[4],hall_05_c_rm); ds_list_add(global.zone_arr[4],hall_05_c_rm);
ds_list_add(global.zone_arr[4],hall_06_a_rm); 
ds_list_add(global.zone_arr[4],hall_06_b_rm);
ds_list_add(global.zone_arr[4],hall_07_a_rm);
ds_list_add(global.zone_arr[4],hall_07_b_rm);
ds_list_add(global.zone_arr[4],hall_08_rm); ds_list_add(global.zone_arr[4],hall_08_rm);
ds_list_add(global.zone_arr[4],hall_09_a_rm);
ds_list_add(global.zone_arr[4],hall_09_b_rm);
ds_list_add(global.zone_arr[4],hall_10_a_rm);
ds_list_add(global.zone_arr[4],hall_10_b_rm);
ds_list_add(global.zone_arr[4],hall_11_a_rm);
ds_list_add(global.zone_arr[4],hall_11_b_rm);
ds_list_add(global.zone_arr[4],hall_12_a_rm);
ds_list_add(global.zone_arr[4],hall_12_b_rm);
ds_list_add(global.zone_arr[4],hall_19_rm); ds_list_add(global.zone_arr[4],hall_19_rm);
ds_list_add(global.zone_arr[4],hall_20_rm); ds_list_add(global.zone_arr[4],hall_20_rm);
ds_list_add(global.zone_arr[4],hall_21_a_rm); ds_list_add(global.zone_arr[4],hall_21_a_rm);
ds_list_add(global.zone_arr[4],hall_21_b_rm); ds_list_add(global.zone_arr[4],hall_21_b_rm);
ds_list_add(global.zone_arr[4],hall_22_rm); ds_list_add(global.zone_arr[4],hall_22_rm);
ds_list_add(global.zone_arr[4],hall_23_rm); ds_list_add(global.zone_arr[4],hall_23_rm);
ds_list_add(global.zone_arr[4],hall_24_rm); ds_list_add(global.zone_arr[4],hall_24_rm);
ds_list_add(global.zone_arr[4],hall_26_rm); ds_list_add(global.zone_arr[4],hall_26_rm);
ds_list_add(global.zone_arr[4],hall_27_rm); ds_list_add(global.zone_arr[4],hall_27_rm);
ds_list_add(global.zone_arr[4],hall_30_rm); ds_list_add(global.zone_arr[4],hall_30_rm);
ds_list_add(global.zone_arr[4],hall_31_rm); ds_list_add(global.zone_arr[4],hall_31_rm);
ds_list_add(global.zone_arr[4],hall_32_rm); ds_list_add(global.zone_arr[4],hall_32_rm);
ds_list_add(global.zone_arr[4],hall_33_rm); ds_list_add(global.zone_arr[4],hall_33_rm);
ds_list_add(global.zone_arr[4],hall_34_rm); ds_list_add(global.zone_arr[4],hall_34_rm);
ds_list_add(global.zone_arr[4],tt_hall_01_rm); ds_list_add(global.zone_arr[4],tt_hall_01_rm);
ds_list_add(global.zone_arr[4],tt_hall_02_rm); ds_list_add(global.zone_arr[4],tt_hall_02_rm);
ds_list_add(global.zone_arr[4],tt_hall_03_rm); ds_list_add(global.zone_arr[4],tt_hall_03_rm);
ds_list_add(global.zone_arr[4],tt_hall_04_rm); ds_list_add(global.zone_arr[4],tt_hall_04_rm);
ds_list_add(global.zone_arr[4],tt_hall_05_rm); ds_list_add(global.zone_arr[4],tt_hall_05_rm);
ds_list_add(global.zone_arr[4],tt_hall_06_rm); ds_list_add(global.zone_arr[4],tt_hall_06_rm);
ds_list_add(global.zone_arr[4],tt_hall_07_rm); ds_list_add(global.zone_arr[4],tt_hall_07_rm);
ds_list_add(global.zone_arr[4],tt_hall_08_rm); ds_list_add(global.zone_arr[4],tt_hall_08_rm);
ds_list_add(global.zone_arr[4],tt_hall_09_rm); ds_list_add(global.zone_arr[4],tt_hall_09_rm);
ds_list_add(global.zone_arr[4],tt_hall_10_rm); ds_list_add(global.zone_arr[4],tt_hall_10_rm);
ds_list_add(global.zone_arr[4],tt_hall_11_rm); ds_list_add(global.zone_arr[4],tt_hall_11_rm);
ds_list_add(global.zone_arr[4],tt_hall_12_rm); ds_list_add(global.zone_arr[4],tt_hall_12_rm);
ds_list_add(global.zone_arr[4],long_hall_01_rm); ds_list_add(global.zone_arr[4],long_hall_01_rm);
ds_list_add(global.zone_arr[4],long_hall_02_rm); ds_list_add(global.zone_arr[4],long_hall_02_rm);
ds_list_add(global.zone_arr[4],long_hall_03_rm); ds_list_add(global.zone_arr[4],long_hall_03_rm);
ds_list_add(global.zone_arr[4],long_hall_04_rm); ds_list_add(global.zone_arr[4],long_hall_04_rm);
ds_list_add(global.zone_arr[4],long_hall_05_rm); ds_list_add(global.zone_arr[4],long_hall_05_rm); ds_list_add(global.zone_arr[4],long_hall_05_rm); ds_list_add(global.zone_arr[4],long_hall_05_rm);
ds_list_add(global.zone_arr[4],long_hall_07_rm); ds_list_add(global.zone_arr[4],long_hall_07_rm);
ds_list_add(global.zone_arr[4],long_hall_08_rm); ds_list_add(global.zone_arr[4],long_hall_08_rm);
ds_list_add(global.zone_arr[4],long_hall_09_rm); ds_list_add(global.zone_arr[4],long_hall_09_rm);
ds_list_add(global.zone_arr[4],long_hall_10_rm); ds_list_add(global.zone_arr[4],long_hall_10_rm);
ds_list_add(global.zone_arr[4],long_hall_11_rm); ds_list_add(global.zone_arr[4],long_hall_11_rm);
ds_list_add(global.zone_arr[4],long_hall_12_rm); ds_list_add(global.zone_arr[4],long_hall_12_rm);
ds_list_add(global.zone_arr[4],w_hall_01_rm); ds_list_add(global.zone_arr[4],w_hall_01_rm);
ds_list_add(global.zone_arr[4],w_hall_02_rm); ds_list_add(global.zone_arr[4],w_hall_02_rm);
ds_list_add(global.zone_arr[4],w_hall_03_rm); ds_list_add(global.zone_arr[4],w_hall_03_rm);
ds_list_add(global.zone_arr[4],w_hall_04_rm); ds_list_add(global.zone_arr[4],w_hall_04_rm);
ds_list_add(global.zone_arr[4],w_hall_05_rm); ds_list_add(global.zone_arr[4],w_hall_05_rm);
ds_list_add(global.zone_arr[4],w_hall_06_rm); ds_list_add(global.zone_arr[4],w_hall_06_rm);
ds_list_add(global.zone_arr[4],w_hall_07_rm); ds_list_add(global.zone_arr[4],w_hall_07_rm);
ds_list_add(global.zone_arr[4],w_hall_08_rm); ds_list_add(global.zone_arr[4],w_hall_08_rm);
ds_list_add(global.zone_arr[4],w_hall_09_rm); ds_list_add(global.zone_arr[4],w_hall_09_rm);
ds_list_add(global.zone_arr[4],w_hall_10_rm); ds_list_add(global.zone_arr[4],w_hall_10_rm);
ds_list_add(global.zone_arr[4],w_hall_11_a_rm); ds_list_add(global.zone_arr[4],w_hall_11_a_rm);
ds_list_add(global.zone_arr[4],w_hall_11_b_rm); ds_list_add(global.zone_arr[4],w_hall_11_b_rm);
ds_list_add(global.zone_arr[4],w_hall_12_rm); ds_list_add(global.zone_arr[4],w_hall_12_rm);
ds_list_add(global.zone_arr[4],w_hall_13_rm); ds_list_add(global.zone_arr[4],w_hall_13_rm);
ds_list_add(global.zone_arr[4],w_hall_14_rm); ds_list_add(global.zone_arr[4],w_hall_14_rm);
ds_list_add(global.zone_arr[4],w_hall_15_rm); ds_list_add(global.zone_arr[4],w_hall_15_rm);

// Zone 5
global.zone_arr[5] = ds_list_create();
ds_list_clear(global.zone_arr[5]);
ds_list_add(global.zone_arr[5],sm_01_rm);
ds_list_add(global.zone_arr[5],sm_02_rm);
ds_list_add(global.zone_arr[5],sm_03_rm);
ds_list_add(global.zone_arr[5],sm_04_rm);
ds_list_add(global.zone_arr[5],sm_05_rm);
ds_list_add(global.zone_arr[5],sm_06_rm);
ds_list_add(global.zone_arr[5],sm_07_rm);
ds_list_add(global.zone_arr[5],sm_08_rm);
ds_list_add(global.zone_arr[5],purp_01_rm);
ds_list_add(global.zone_arr[5],purp_02_rm);
ds_list_add(global.zone_arr[5],purp_03_rm);
ds_list_add(global.zone_arr[5],purp_04_rm);
ds_list_add(global.zone_arr[5],purp_05_rm);
ds_list_add(global.zone_arr[5],purp_06_rm);
ds_list_add(global.zone_arr[5],sm_15_rm);
ds_list_add(global.zone_arr[5],sm_16_rm);
ds_list_add(global.zone_arr[5],sm_17_rm);
ds_list_add(global.zone_arr[5],sm_18_rm);
ds_list_add(global.zone_arr[5],sm_19_rm);
ds_list_add(global.zone_arr[5],sm_20_rm);
/*
ds_list_add(global.zone_arr[5],bed_01_rm);
ds_list_add(global.zone_arr[5],bed_02_rm);
ds_list_add(global.zone_arr[5],bed_03_rm);
ds_list_add(global.zone_arr[5],bed_04_rm);
ds_list_add(global.zone_arr[5],bed_05_rm);
ds_list_add(global.zone_arr[5],bed_06_rm);
ds_list_add(global.zone_arr[5],bed_07_rm);
ds_list_add(global.zone_arr[5],bed_08_rm);
ds_list_add(global.zone_arr[5],stor_01_rm);
ds_list_add(global.zone_arr[5],stor_02_rm);
ds_list_add(global.zone_arr[5],stor_03_rm);
ds_list_add(global.zone_arr[5],stor_04_rm);
ds_list_add(global.zone_arr[5],stor_05_rm);
ds_list_add(global.zone_arr[5],stor_06_rm);
ds_list_add(global.zone_arr[5],stor_07_rm);
ds_list_add(global.zone_arr[5],stor_08_rm);
ds_list_add(global.zone_arr[5],sm_lab_01_rm);
ds_list_add(global.zone_arr[5],sm_lab_02_rm);
ds_list_add(global.zone_arr[5],sm_lab_03_rm);
ds_list_add(global.zone_arr[5],sm_lab_04_rm);
ds_list_add(global.zone_arr[5],sm_lab_05_rm);
ds_list_add(global.zone_arr[5],sm_lab_06_rm);
ds_list_add(global.zone_arr[5],sm_lab_07_rm);
ds_list_add(global.zone_arr[5],sm_lab_08_rm);
ds_list_add(global.zone_arr[5],sm_lab_09_rm);
ds_list_add(global.zone_arr[5],sm_lab_10_rm);
ds_list_add(global.zone_arr[5],sm_lab_11_rm);
ds_list_add(global.zone_arr[5],sm_lab_12_rm);
ds_list_add(global.zone_arr[5],sm_lab_13_rm);
ds_list_add(global.zone_arr[5],sm_lab_14_rm);
ds_list_add(global.zone_arr[5],sm_lab_15_rm);
ds_list_add(global.zone_arr[5],sm_lab_16_rm);
*/
ds_list_add(global.zone_arr[5],jail_01_rm);
ds_list_add(global.zone_arr[5],jail_02_rm);
ds_list_add(global.zone_arr[5],jail_03_rm);
ds_list_add(global.zone_arr[5],jail_04_rm);
ds_list_add(global.zone_arr[5],jail_05_rm);
ds_list_add(global.zone_arr[5],jail_06_a_rm);
ds_list_add(global.zone_arr[5],jail_07_a_rm);
ds_list_add(global.zone_arr[5],jail_08_rm);
ds_list_add(global.zone_arr[5],jail_09_rm);
ds_list_add(global.zone_arr[5],jail_10_a_rm);
ds_list_add(global.zone_arr[5],jail_11_rm);
ds_list_add(global.zone_arr[5],jail_12_rm);
ds_list_add(global.zone_arr[5],jail_13_rm);
ds_list_add(global.zone_arr[5],jail_14_rm);
ds_list_add(global.zone_arr[5],jail_15_rm);
ds_list_add(global.zone_arr[5],jail_16_rm);
ds_list_add(global.zone_arr[5],hall_01_rm);
ds_list_add(global.zone_arr[5],hall_03_rm);
ds_list_add(global.zone_arr[5],hall_19_rm);
ds_list_add(global.zone_arr[5],hall_24_rm);
// Zone 6
global.zone_arr[6] = ds_list_create();
ds_list_clear(global.zone_arr[6]);
/*
ds_list_add(global.zone_arr[6],sm_lab_01_rm);
ds_list_add(global.zone_arr[6],sm_lab_02_rm);
ds_list_add(global.zone_arr[6],sm_lab_03_rm);
ds_list_add(global.zone_arr[6],sm_lab_04_rm);
ds_list_add(global.zone_arr[6],sm_lab_05_rm);
ds_list_add(global.zone_arr[6],sm_lab_06_rm);
ds_list_add(global.zone_arr[6],sm_lab_07_rm);
ds_list_add(global.zone_arr[6],sm_lab_08_rm);
ds_list_add(global.zone_arr[6],sm_lab_09_rm);
ds_list_add(global.zone_arr[6],sm_lab_10_rm);
ds_list_add(global.zone_arr[6],sm_lab_11_rm);
ds_list_add(global.zone_arr[6],sm_lab_12_rm);
ds_list_add(global.zone_arr[6],sm_lab_13_rm);
ds_list_add(global.zone_arr[6],sm_lab_14_rm);
ds_list_add(global.zone_arr[6],sm_lab_15_rm);
ds_list_add(global.zone_arr[6],sm_lab_16_rm);
*/
ds_list_add(global.zone_arr[6],w_hall_01_rm);
ds_list_add(global.zone_arr[6],w_hall_02_rm);
ds_list_add(global.zone_arr[6],w_hall_03_rm);
ds_list_add(global.zone_arr[6],w_hall_04_rm);
ds_list_add(global.zone_arr[6],w_hall_05_rm);
ds_list_add(global.zone_arr[6],w_hall_06_rm);
ds_list_add(global.zone_arr[6],w_hall_07_rm);
ds_list_add(global.zone_arr[6],w_hall_08_rm);
ds_list_add(global.zone_arr[6],w_hall_09_rm);
ds_list_add(global.zone_arr[6],w_hall_10_rm);
ds_list_add(global.zone_arr[6],w_hall_11_a_rm);
ds_list_add(global.zone_arr[6],w_hall_11_b_rm);
ds_list_add(global.zone_arr[6],w_hall_12_rm);
ds_list_add(global.zone_arr[6],w_hall_13_rm);
ds_list_add(global.zone_arr[6],w_hall_14_rm);
ds_list_add(global.zone_arr[6],w_hall_15_rm);
ds_list_add(global.zone_arr[6],med_01_rm);
ds_list_add(global.zone_arr[6],med_02_rm);
ds_list_add(global.zone_arr[6],med_03_rm);
ds_list_add(global.zone_arr[6],med_04_rm);
ds_list_add(global.zone_arr[6],med_05_rm);
ds_list_add(global.zone_arr[6],med_06_rm);
ds_list_add(global.zone_arr[6],med_07_rm);
ds_list_add(global.zone_arr[6],med_08_rm);
ds_list_add(global.zone_arr[6],med_09_rm);
ds_list_add(global.zone_arr[6],med_10_rm);
ds_list_add(global.zone_arr[6],med_11_rm);
ds_list_add(global.zone_arr[6],tt_hall_01_rm);
ds_list_add(global.zone_arr[6],tt_hall_02_rm);
ds_list_add(global.zone_arr[6],tt_hall_03_rm);
ds_list_add(global.zone_arr[6],tt_hall_04_rm);
ds_list_add(global.zone_arr[6],tt_hall_05_rm);
ds_list_add(global.zone_arr[6],tt_hall_06_rm);
ds_list_add(global.zone_arr[6],tt_hall_07_rm);
ds_list_add(global.zone_arr[6],tt_hall_08_rm);
ds_list_add(global.zone_arr[6],tt_hall_09_rm);
ds_list_add(global.zone_arr[6],tt_hall_10_rm);
ds_list_add(global.zone_arr[6],tt_hall_11_rm);
ds_list_add(global.zone_arr[6],tt_hall_12_rm);
ds_list_add(global.zone_arr[6],fish_01_rm);
ds_list_add(global.zone_arr[6],fish_02_rm);
ds_list_add(global.zone_arr[6],fish_03_rm);
ds_list_add(global.zone_arr[6],fish_04_rm);
ds_list_add(global.zone_arr[6],fish_05_rm);
ds_list_add(global.zone_arr[6],fish_06_rm);
ds_list_add(global.zone_arr[6],fish_07_rm);
ds_list_add(global.zone_arr[6],fish_08_rm);
ds_list_add(global.zone_arr[6],fish_09_rm);
ds_list_add(global.zone_arr[6],fish_10_rm);
ds_list_add(global.zone_arr[6],fish_11_rm);
ds_list_add(global.zone_arr[6],fish_12_rm);
ds_list_add(global.zone_arr[6],fish_13_rm);
ds_list_add(global.zone_arr[6],fish_14_rm);
ds_list_add(global.zone_arr[6],fish_15_rm);
ds_list_add(global.zone_arr[6],fish_16_rm);
// Zone 7
global.zone_arr[7] = ds_list_create();
ds_list_clear(global.zone_arr[7]);
ds_list_add(global.zone_arr[7],hall_01_rm); ds_list_add(global.zone_arr[7],hall_01_rm);
ds_list_add(global.zone_arr[7],hall_02_rm);
ds_list_add(global.zone_arr[7],hall_03_rm);
ds_list_add(global.zone_arr[7],hall_04_rm);
ds_list_add(global.zone_arr[7],hall_05_rm);
ds_list_add(global.zone_arr[7],sm_01_rm);
ds_list_add(global.zone_arr[7],sm_02_rm);
ds_list_add(global.zone_arr[7],sm_03_rm);
ds_list_add(global.zone_arr[7],sm_04_rm);
ds_list_add(global.zone_arr[7],sm_05_rm);
ds_list_add(global.zone_arr[7],sm_06_rm);
ds_list_add(global.zone_arr[7],sm_07_rm);
ds_list_add(global.zone_arr[7],sm_08_rm);
ds_list_add(global.zone_arr[7],purp_01_rm);
ds_list_add(global.zone_arr[7],purp_02_rm);
ds_list_add(global.zone_arr[7],purp_03_rm);
ds_list_add(global.zone_arr[7],purp_04_rm);
ds_list_add(global.zone_arr[7],purp_05_rm);
ds_list_add(global.zone_arr[7],purp_06_rm);
ds_list_add(global.zone_arr[7],sm_15_rm);
ds_list_add(global.zone_arr[7],sm_16_rm);
ds_list_add(global.zone_arr[7],sm_17_rm);
ds_list_add(global.zone_arr[7],sm_18_rm);
ds_list_add(global.zone_arr[7],sm_19_rm);
ds_list_add(global.zone_arr[7],sm_20_rm);
/*
ds_list_add(global.zone_arr[7],bed_01_rm);
ds_list_add(global.zone_arr[7],bed_02_rm);
ds_list_add(global.zone_arr[7],bed_03_rm);
ds_list_add(global.zone_arr[7],bed_04_rm);
ds_list_add(global.zone_arr[7],bed_05_rm);
ds_list_add(global.zone_arr[7],bed_06_rm);
ds_list_add(global.zone_arr[7],bed_07_rm);
ds_list_add(global.zone_arr[7],bed_08_rm);
ds_list_add(global.zone_arr[7],stor_01_rm);
ds_list_add(global.zone_arr[7],stor_02_rm);
ds_list_add(global.zone_arr[7],stor_03_rm);
ds_list_add(global.zone_arr[7],stor_04_rm);
ds_list_add(global.zone_arr[7],stor_05_rm);
ds_list_add(global.zone_arr[7],stor_06_rm);
ds_list_add(global.zone_arr[7],stor_07_rm);
ds_list_add(global.zone_arr[7],stor_08_rm);
ds_list_add(global.zone_arr[7],hotel_01_rm);
ds_list_add(global.zone_arr[7],hotel_02_rm);
ds_list_add(global.zone_arr[7],hotel_03_rm);
ds_list_add(global.zone_arr[7],hotel_04_rm);
ds_list_add(global.zone_arr[7],hotel_05_rm);
ds_list_add(global.zone_arr[7],hotel_06_rm);
ds_list_add(global.zone_arr[7],hotel_07_rm);
ds_list_add(global.zone_arr[7],hotel_08_rm);
ds_list_add(global.zone_arr[7],hotel_09_rm);
ds_list_add(global.zone_arr[7],hotel_10_rm);
ds_list_add(global.zone_arr[7],hotel_11_rm);
ds_list_add(global.zone_arr[7],hotel_12_rm);
ds_list_add(global.zone_arr[7],hotel_13_rm);
ds_list_add(global.zone_arr[7],hotel_14_rm);
ds_list_add(global.zone_arr[7],hotel_15_rm);
ds_list_add(global.zone_arr[7],hotel_16_rm);
*/
ds_list_add(global.zone_arr[7],tt_hall_01_rm);
ds_list_add(global.zone_arr[7],tt_hall_02_rm);
ds_list_add(global.zone_arr[7],tt_hall_03_rm);
ds_list_add(global.zone_arr[7],tt_hall_04_rm);
ds_list_add(global.zone_arr[7],tt_hall_05_rm);
ds_list_add(global.zone_arr[7],tt_hall_06_rm);
ds_list_add(global.zone_arr[7],tt_hall_07_rm);
ds_list_add(global.zone_arr[7],tt_hall_08_rm);
ds_list_add(global.zone_arr[7],tt_hall_09_rm);
ds_list_add(global.zone_arr[7],tt_hall_10_rm);
ds_list_add(global.zone_arr[7],tt_hall_11_rm);
ds_list_add(global.zone_arr[7],tt_hall_12_rm);
// Zone 8
global.zone_arr[8] = ds_list_create();
ds_list_clear(global.zone_arr[8]);
ds_list_add(global.zone_arr[8],thin_hall_01_rm);
ds_list_add(global.zone_arr[8],thin_hall_02_rm);
ds_list_add(global.zone_arr[8],thin_hall_03_rm);
ds_list_add(global.zone_arr[8],thin_hall_04_rm);
ds_list_add(global.zone_arr[8],thin_hall_05_rm);
ds_list_add(global.zone_arr[8],thin_hall_06_rm);
ds_list_add(global.zone_arr[8],thin_hall_07_rm);
ds_list_add(global.zone_arr[8],thin_hall_08_rm);
ds_list_add(global.zone_arr[8],thin_hall_09_rm);
ds_list_add(global.zone_arr[8],thin_hall_10_rm);
ds_list_add(global.zone_arr[8],thin_hall_11_rm);
ds_list_add(global.zone_arr[8],thin_hall_12_rm);
ds_list_add(global.zone_arr[8],thin_hall_13_rm);
ds_list_add(global.zone_arr[8],thin_hall_14_rm);
ds_list_add(global.zone_arr[8],thin_hall_15_rm);
ds_list_add(global.zone_arr[8],thin_hall_16_rm);
ds_list_add(global.zone_arr[8],thin_hall_01_rm);
ds_list_add(global.zone_arr[8],med_s_01_rm);
ds_list_add(global.zone_arr[8],med_s_02_rm);
ds_list_add(global.zone_arr[8],med_s_03_rm);
ds_list_add(global.zone_arr[8],med_s_04_rm);
ds_list_add(global.zone_arr[8],med_s_05_rm);
ds_list_add(global.zone_arr[8],med_s_06_rm);
ds_list_add(global.zone_arr[8],med_s_07_rm);
ds_list_add(global.zone_arr[8],med_s_08_rm);
ds_list_add(global.zone_arr[8],med_s_09_rm);
ds_list_add(global.zone_arr[8],med_s_10_rm);
ds_list_add(global.zone_arr[8],med_s_11_rm);
ds_list_add(global.zone_arr[8],med_s_12_rm);
ds_list_add(global.zone_arr[8],long_hall_01_rm);
ds_list_add(global.zone_arr[8],long_hall_02_rm);
ds_list_add(global.zone_arr[8],long_hall_03_rm);
ds_list_add(global.zone_arr[8],long_hall_04_rm);
ds_list_add(global.zone_arr[8],long_hall_05_rm); ds_list_add(global.zone_arr[8],long_hall_05_rm);
ds_list_add(global.zone_arr[8],long_hall_07_rm);
ds_list_add(global.zone_arr[8],long_hall_08_rm);
ds_list_add(global.zone_arr[8],long_hall_09_rm);
ds_list_add(global.zone_arr[8],long_hall_10_rm);
ds_list_add(global.zone_arr[8],long_hall_11_rm);
ds_list_add(global.zone_arr[8],long_hall_12_rm);
ds_list_add(global.zone_arr[8],sm_01_rm);
ds_list_add(global.zone_arr[8],sm_02_rm);
ds_list_add(global.zone_arr[8],sm_03_rm);
ds_list_add(global.zone_arr[8],sm_04_rm);
ds_list_add(global.zone_arr[8],sm_05_rm);
ds_list_add(global.zone_arr[8],sm_06_rm);
ds_list_add(global.zone_arr[8],sm_07_rm);
ds_list_add(global.zone_arr[8],sm_08_rm);
ds_list_add(global.zone_arr[8],purp_01_rm);
ds_list_add(global.zone_arr[8],purp_02_rm);
ds_list_add(global.zone_arr[8],purp_03_rm);
ds_list_add(global.zone_arr[8],purp_04_rm);
ds_list_add(global.zone_arr[8],purp_05_rm);
ds_list_add(global.zone_arr[8],purp_06_rm);
ds_list_add(global.zone_arr[8],sm_15_rm);
ds_list_add(global.zone_arr[8],sm_16_rm);
ds_list_add(global.zone_arr[8],sm_17_rm);
ds_list_add(global.zone_arr[8],sm_18_rm);
ds_list_add(global.zone_arr[8],sm_19_rm);
ds_list_add(global.zone_arr[8],sm_20_rm);
ds_list_add(global.zone_arr[8],sc_hall_05_rm);
ds_list_add(global.zone_arr[8],sc_hall_06_rm);
ds_list_add(global.zone_arr[8],sc_hall_10_rm);
ds_list_add(global.zone_arr[8],sc_hall_11_rm);
ds_list_add(global.zone_arr[8],sc_hall_12_rm);
// Zone 9, every
global.zone_arr[9] = ds_list_create();
ds_list_clear(global.zone_arr[9]);
ds_list_add(global.zone_arr[9],big_01_rm);
ds_list_add(global.zone_arr[9],big_02_rm);
ds_list_add(global.zone_arr[9],big_03_rm);
ds_list_add(global.zone_arr[9],big_04_rm);
ds_list_add(global.zone_arr[9],big_05_rm);
ds_list_add(global.zone_arr[9],big_06_rm);
ds_list_add(global.zone_arr[9],big_07_rm);
ds_list_add(global.zone_arr[9],big_08_rm);
ds_list_add(global.zone_arr[9],engine_01_rm);
ds_list_add(global.zone_arr[9],engine_02_rm);
ds_list_add(global.zone_arr[9],engine_03_rm);
ds_list_add(global.zone_arr[9],engine_04_rm);
ds_list_add(global.zone_arr[9],engine_05_rm);
ds_list_add(global.zone_arr[9],engine_06_rm);
ds_list_add(global.zone_arr[9],engine_07_rm);
ds_list_add(global.zone_arr[9],engine_08_rm);
ds_list_add(global.zone_arr[9],engine_09_rm);
ds_list_add(global.zone_arr[9],engine_10_rm);
ds_list_add(global.zone_arr[9],engine_11_rm);
ds_list_add(global.zone_arr[9],engine_12_rm);
ds_list_add(global.zone_arr[9],engine_13_rm);
ds_list_add(global.zone_arr[9],engine_14_rm);
ds_list_add(global.zone_arr[9],engine_15_rm);
ds_list_add(global.zone_arr[9],engine_16_rm);
ds_list_add(global.zone_arr[9],fish_01_rm);
ds_list_add(global.zone_arr[9],fish_02_rm);
ds_list_add(global.zone_arr[9],fish_03_rm);
ds_list_add(global.zone_arr[9],fish_04_rm);
ds_list_add(global.zone_arr[9],fish_05_rm);
ds_list_add(global.zone_arr[9],fish_06_rm);
ds_list_add(global.zone_arr[9],fish_07_rm);
ds_list_add(global.zone_arr[9],fish_08_rm);
ds_list_add(global.zone_arr[9],fish_09_rm);
ds_list_add(global.zone_arr[9],fish_10_rm);
ds_list_add(global.zone_arr[9],fish_11_rm);
ds_list_add(global.zone_arr[9],fish_12_rm);
ds_list_add(global.zone_arr[9],fish_13_rm);
ds_list_add(global.zone_arr[9],fish_14_rm);
ds_list_add(global.zone_arr[9],fish_15_rm);
ds_list_add(global.zone_arr[9],fish_16_rm);
ds_list_add(global.zone_arr[9],hall_01_rm);
ds_list_add(global.zone_arr[9],hall_02_a_rm);
ds_list_add(global.zone_arr[9],hall_02_a_gold_rm);
ds_list_add(global.zone_arr[9],hall_02_b_rm);
ds_list_add(global.zone_arr[9],hall_03_rm);
ds_list_add(global.zone_arr[9],hall_04_rm);
ds_list_add(global.zone_arr[9],hall_05_a_rm);
ds_list_add(global.zone_arr[9],hall_05_b_rm);
ds_list_add(global.zone_arr[9],hall_05_c_rm);
ds_list_add(global.zone_arr[9],hall_06_a_rm);
ds_list_add(global.zone_arr[9],hall_06_b_rm);
ds_list_add(global.zone_arr[9],hall_07_a_rm);
ds_list_add(global.zone_arr[9],hall_07_b_rm);
ds_list_add(global.zone_arr[9],hall_08_rm);
ds_list_add(global.zone_arr[9],hall_09_a_rm);
ds_list_add(global.zone_arr[9],hall_09_b_rm);
ds_list_add(global.zone_arr[9],hall_10_a_rm);
ds_list_add(global.zone_arr[9],hall_10_a_gold_rm);
ds_list_add(global.zone_arr[9],hall_10_b_rm);
ds_list_add(global.zone_arr[9],hall_11_a_rm);
ds_list_add(global.zone_arr[9],hall_11_b_rm);
ds_list_add(global.zone_arr[9],hall_12_a_rm);
ds_list_add(global.zone_arr[9],hall_12_b_rm);
ds_list_add(global.zone_arr[9],hall_13_rm);
ds_list_add(global.zone_arr[9],hall_13_ungold_rm);
ds_list_add(global.zone_arr[9],hall_14_a_rm);
ds_list_add(global.zone_arr[9],hall_14_b_rm);
ds_list_add(global.zone_arr[9],hall_15_a_rm);
ds_list_add(global.zone_arr[9],hall_15_b_rm);
ds_list_add(global.zone_arr[9],hall_16_a_rm);
ds_list_add(global.zone_arr[9],hall_16_a_lass_rm);
ds_list_add(global.zone_arr[9],hall_16_b_rm);
ds_list_add(global.zone_arr[9],hall_17_a_rm);
ds_list_add(global.zone_arr[9],hall_17_b_rm);
ds_list_add(global.zone_arr[9],hall_19_rm);
ds_list_add(global.zone_arr[9],hall_20_rm);
ds_list_add(global.zone_arr[9],hall_21_a_rm);
ds_list_add(global.zone_arr[9],hall_21_b_rm);
ds_list_add(global.zone_arr[9],hall_22_rm);
ds_list_add(global.zone_arr[9],hall_23_rm);
ds_list_add(global.zone_arr[9],hall_24_rm);
ds_list_add(global.zone_arr[9],hall_26_rm);
ds_list_add(global.zone_arr[9],hall_27_rm);
ds_list_add(global.zone_arr[9],hall_30_rm);
ds_list_add(global.zone_arr[9],hall_31_rm);
ds_list_add(global.zone_arr[9],hall_31_gold_rm);
ds_list_add(global.zone_arr[9],hall_32_rm);
ds_list_add(global.zone_arr[9],hall_33_rm);
ds_list_add(global.zone_arr[9],hall_34_rm);
ds_list_add(global.zone_arr[9],jail_01_rm);
ds_list_add(global.zone_arr[9],jail_02_rm);
ds_list_add(global.zone_arr[9],jail_03_rm);
ds_list_add(global.zone_arr[9],jail_04_rm);
ds_list_add(global.zone_arr[9],jail_05_rm);
ds_list_add(global.zone_arr[9],jail_06_a_rm);
ds_list_add(global.zone_arr[9],jail_06_b_rm);
ds_list_add(global.zone_arr[9],jail_07_a_rm);
ds_list_add(global.zone_arr[9],jail_07_b_rm);
ds_list_add(global.zone_arr[9],jail_07_c_rm);
ds_list_add(global.zone_arr[9],jail_08_rm);
ds_list_add(global.zone_arr[9],jail_09_rm);
ds_list_add(global.zone_arr[9],jail_10_a_rm);
ds_list_add(global.zone_arr[9],jail_11_rm);
ds_list_add(global.zone_arr[9],jail_12_rm);
ds_list_add(global.zone_arr[9],jail_13_rm);
ds_list_add(global.zone_arr[9],jail_14_rm);
ds_list_add(global.zone_arr[9],jail_15_rm);
ds_list_add(global.zone_arr[9],jail_15_gold_rm);
ds_list_add(global.zone_arr[9],jail_16_rm);
ds_list_add(global.zone_arr[9],long_hall_01_rm);
ds_list_add(global.zone_arr[9],long_hall_02_rm);
ds_list_add(global.zone_arr[9],long_hall_03_rm);
ds_list_add(global.zone_arr[9],long_hall_04_rm);
ds_list_add(global.zone_arr[9],long_hall_05_rm);
ds_list_add(global.zone_arr[9],long_hall_05_ungold_rm);
ds_list_add(global.zone_arr[9],long_hall_07_rm);
ds_list_add(global.zone_arr[9],long_hall_08_rm);
ds_list_add(global.zone_arr[9],long_hall_09_rm);
ds_list_add(global.zone_arr[9],long_hall_10_rm);
ds_list_add(global.zone_arr[9],long_hall_11_rm);
ds_list_add(global.zone_arr[9],long_hall_12_rm);
ds_list_add(global.zone_arr[9],med_01_rm);
ds_list_add(global.zone_arr[9],med_02_rm);
ds_list_add(global.zone_arr[9],med_03_rm);
ds_list_add(global.zone_arr[9],med_04_rm);
ds_list_add(global.zone_arr[9],med_05_rm);
ds_list_add(global.zone_arr[9],med_06_rm);
ds_list_add(global.zone_arr[9],med_07_rm);
ds_list_add(global.zone_arr[9],med_08_rm);
ds_list_add(global.zone_arr[9],med_09_rm);
ds_list_add(global.zone_arr[9],med_10_rm);
ds_list_add(global.zone_arr[9],med_11_rm);
ds_list_add(global.zone_arr[9],med_s_01_rm);
ds_list_add(global.zone_arr[9],med_s_02_rm);
ds_list_add(global.zone_arr[9],med_s_03_rm);
ds_list_add(global.zone_arr[9],med_s_04_rm);
ds_list_add(global.zone_arr[9],med_s_05_rm);
ds_list_add(global.zone_arr[9],med_s_06_rm);
ds_list_add(global.zone_arr[9],med_s_07_a_rm);
ds_list_add(global.zone_arr[9],med_s_07_b_rm);
ds_list_add(global.zone_arr[9],med_s_08_rm);
ds_list_add(global.zone_arr[9],med_s_09_rm);
ds_list_add(global.zone_arr[9],med_s_10_rm);
ds_list_add(global.zone_arr[9],med_s_11_rm);
ds_list_add(global.zone_arr[9],med_s_12_rm);
ds_list_add(global.zone_arr[9],purp_01_rm);
ds_list_add(global.zone_arr[9],purp_02_rm);
ds_list_add(global.zone_arr[9],purp_03_rm);
ds_list_add(global.zone_arr[9],purp_04_rm);
ds_list_add(global.zone_arr[9],purp_05_rm);
ds_list_add(global.zone_arr[9],purp_06_rm);
ds_list_add(global.zone_arr[9],sc_hall_01_rm);
ds_list_add(global.zone_arr[9],sc_hall_02_rm);
ds_list_add(global.zone_arr[9],sc_hall_03_rm);
ds_list_add(global.zone_arr[9],sc_hall_04_rm);
ds_list_add(global.zone_arr[9],sc_hall_05_rm);
ds_list_add(global.zone_arr[9],sc_hall_06_rm);
ds_list_add(global.zone_arr[9],sc_hall_07_rm);
ds_list_add(global.zone_arr[9],sc_hall_08_rm);
ds_list_add(global.zone_arr[9],sc_hall_09_rm);
ds_list_add(global.zone_arr[9],sc_hall_10_rm);
ds_list_add(global.zone_arr[9],sc_hall_11_rm);
ds_list_add(global.zone_arr[9],sc_hall_12_rm);
ds_list_add(global.zone_arr[9],sm_01_rm);
ds_list_add(global.zone_arr[9],sm_02_rm);
ds_list_add(global.zone_arr[9],sm_03_rm);
ds_list_add(global.zone_arr[9],sm_04_rm);
ds_list_add(global.zone_arr[9],sm_05_rm);
ds_list_add(global.zone_arr[9],sm_06_rm);
ds_list_add(global.zone_arr[9],sm_07_rm);
ds_list_add(global.zone_arr[9],sm_08_rm);
ds_list_add(global.zone_arr[9],sm_15_rm);
ds_list_add(global.zone_arr[9],sm_16_rm);
ds_list_add(global.zone_arr[9],sm_17_rm);
ds_list_add(global.zone_arr[9],sm_18_rm);
ds_list_add(global.zone_arr[9],sm_19_rm);
ds_list_add(global.zone_arr[9],sm_20_rm);
ds_list_add(global.zone_arr[9],thin_hall_01_rm);
ds_list_add(global.zone_arr[9],thin_hall_02_rm);
ds_list_add(global.zone_arr[9],thin_hall_03_rm);
ds_list_add(global.zone_arr[9],thin_hall_04_rm);
ds_list_add(global.zone_arr[9],thin_hall_05_rm);
ds_list_add(global.zone_arr[9],thin_hall_06_rm);
ds_list_add(global.zone_arr[9],thin_hall_07_rm);
ds_list_add(global.zone_arr[9],thin_hall_08_rm);
ds_list_add(global.zone_arr[9],thin_hall_09_rm);
ds_list_add(global.zone_arr[9],thin_hall_10_rm);
ds_list_add(global.zone_arr[9],thin_hall_11_rm);
ds_list_add(global.zone_arr[9],thin_hall_12_rm);
ds_list_add(global.zone_arr[9],thin_hall_13_rm);
ds_list_add(global.zone_arr[9],thin_hall_14_rm);
ds_list_add(global.zone_arr[9],thin_hall_15_rm);
ds_list_add(global.zone_arr[9],thin_hall_16_rm);
ds_list_add(global.zone_arr[9],tt_hall_01_rm);
ds_list_add(global.zone_arr[9],tt_hall_02_rm);
ds_list_add(global.zone_arr[9],tt_hall_03_rm);
ds_list_add(global.zone_arr[9],tt_hall_04_rm);
ds_list_add(global.zone_arr[9],tt_hall_05_rm);
ds_list_add(global.zone_arr[9],tt_hall_06_rm);
ds_list_add(global.zone_arr[9],tt_hall_07_rm);
ds_list_add(global.zone_arr[9],tt_hall_08_rm);
ds_list_add(global.zone_arr[9],tt_hall_09_rm);
ds_list_add(global.zone_arr[9],tt_hall_10_rm);
ds_list_add(global.zone_arr[9],tt_hall_11_rm);
ds_list_add(global.zone_arr[9],tt_hall_12_rm);
ds_list_add(global.zone_arr[9],w_hall_01_rm);
ds_list_add(global.zone_arr[9],w_hall_02_rm);
ds_list_add(global.zone_arr[9],w_hall_03_rm);
ds_list_add(global.zone_arr[9],w_hall_04_rm);
ds_list_add(global.zone_arr[9],w_hall_05_rm);
ds_list_add(global.zone_arr[9],w_hall_06_rm);
ds_list_add(global.zone_arr[9],w_hall_07_rm);
ds_list_add(global.zone_arr[9],w_hall_08_rm);
ds_list_add(global.zone_arr[9],w_hall_09_rm);
ds_list_add(global.zone_arr[9],w_hall_09_lass_rm);
ds_list_add(global.zone_arr[9],w_hall_10_rm);
ds_list_add(global.zone_arr[9],w_hall_11_a_rm);
ds_list_add(global.zone_arr[9],w_hall_11_b_rm);
ds_list_add(global.zone_arr[9],w_hall_12_rm);
ds_list_add(global.zone_arr[9],w_hall_13_rm);
ds_list_add(global.zone_arr[9],w_hall_14_rm);
ds_list_add(global.zone_arr[9],w_hall_15_rm);
// Room
global.rm_list_var = ds_list_create();
ds_list_clear(global.rm_list_var);
global.zone_var = global.zone_arr[0];